apiVersion: v1
kind: Service
metadata:
  name: WebApp 
  labels:
    name: WebApp
spec:
  type: "{{.Values.service.type}}"
  ports:
    - name: http
      port: {{.Values.service.port}}
      targetPort: {{.Values.service.port}}
  selector:
    app: WebApp